### ISSUE TITLE
手机拍照返回的是UImage对象，如何适配你里面的renderSelectImages(images: [PHAsset])方法呢

### ISSUE THREAD

**Issue by googlb** [apptut/PhotoPicker#1]
手机拍照返回的是UImage对象，如何适配你里面的renderSelectImages(images: [PHAsset])方法呢

**Comment by apptut** [comment]
@googlb 可用两种方式实现，

1. 修改selectImageModel:[PHAsset] 为 selectImageModel: [UIImage], 此方式需要你修改选择回调部分代码
2. 或先保存UIImage对象到相册，然后使用PHPhotoLibrary相关方法找到该图片的PHAsset对象，可参考此项目的拍照部分代码
