### ISSUE TITLE
1. swift3.0版本，删除已选择图片，删除后的图片仍然在照片选择界面上显示。2.能不能在storyBoard照片选择界面勾选Under Top Bars，让导航栏变为为正常白色。感谢

### ISSUE THREAD

**Issue by iamsea** [apptut/PhotoPicker#2]

**Comment by 3823368** [comment]
是的

**Comment by IAskWind** [comment]
看了代码，在siglephoto……的controller里面的方法 eventRemoveImage， 加一句即可self.sourceDelegate?.triggerRefresh = true，作者已经写的很好，希望提供pod库

**Comment by apptut** [comment]
@iamsea 问题1已结修复，问题二不是很清楚你需求，你指的的导航栏具体是指那些页面的导航栏，能否相详细描述一下

**Comment by apptut** [comment]
@IAskWind 多谢指正，自己也已经修复自此问题，此项目库因为涉及部分ui资源，原先并未打算制作pod库
