### ISSUE TITLE
你好 demo 里不能拿到图片的名字和地址

### ISSUE THREAD

**Issue by kmheike** [apptut/PhotoPicker#6]
你好 demo 里不能拿到图片的名字和地址我想转成 base64的    func getdata(model: PhotoImageModel) {
这个 方法就不会走方便看看吗

**Comment by apptut** [comment]
嗨，不是太明白你的意思，我大概重复一下你的问题，你想表达的是：“”想获取图片路径目的使用来获取图片的base64格式内容？“

如果是这个问题，我的回答是：我这个demo封装的PhotoImageModel对象下，data是PHAsset类型，你可以使用PHImageManager的相关方法从PHAsset中获取图片原路径，也可以从PHAsset中直接获取原图片内容直接转为Base64格式，详细可参考PHImageManager使用方法。

可参考这篇如下两个链接：

- https://stackoverflow.com/questions/43968082/get-base64-photo-from-ios-photo-library-uri
- https://stackoverflow.com/questions/27854937/ios8-photos-framework-how-to-get-the-nameor-filename-of-a-phasset
